parameters:
    database_driver: pdo_sqlite
    database_name: tsk_users
    database_user: tsk_admin
    database_password: null
    database_path: task.sqlite3
    database_memory: false
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
